# Generated by Django 4.2.2 on 2023-07-03 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pin_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pin',
            options={'ordering': ('-created_at',)},
        ),
    ]
