# Generated by Django 4.2.2 on 2023-07-16 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0007_alter_follower_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='follower',
            unique_together={('followed_by', 'followed_to')},
        ),
    ]
